version: "3"

services:
  mysql:
    image: mysql:5
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql

    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_HOST: db # Nome do service logo abaixo
      PORT: '3000'
   

 # Serviço que irá rodar o banco de dados
  db:
    container_name: store_manager_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # Garanta que não haverá conflitos de porta com um banco que esteja
      # rodando localmente
      - 3306:3306      

# Lista de redes que os containeres irão utilizar
networks:
  # Rede padrão, criada automaticamente
  default:
    # Dá um nome específico à rede padrão
    name: store_manager_net

volumes:
  node_modules:

